### ISSUE TITLE
青龙面板运行脚本报错

### ISSUE THREAD

**Issue by Theoshen** [Chasing66/smzdm_bot#59]
什么值得买签到
## 开始执行... 2023-12-04 17:58:12

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
2023-12-04 17:58:18.820 | INFO     | __main__:load_conf:25 - Get configration from env
Traceback (most recent call last):
  File "/ql/data/repo/Chasing66_smzdm_bot/app/main.py", line 81, in <module>
    main()
  File "/ql/data/repo/Chasing66_smzdm_bot/app/main.py", line 69, in main
    msg += tasks.checkin()
  File "/ql/data/repo/Chasing66_smzdm_bot/app/utils/smzdm_tasks.py", line 15, in checkin
    resp = self.bot.request("POST", url)
  File "/ql/data/repo/Chasing66_smzdm_bot/app/utils/smzdm_bot.py", line 92, in request
    data = self.data(extra_data)
  File "/ql/data/repo/Chasing66_smzdm_bot/app/utils/smzdm_bot.py", line 79, in data
    "f": self.cookies_dict["device_smzdm"],
KeyError: 'device_smzdm'

## 执行结束... 2023-12-04 17:58:23  耗时 11 秒　　　

只设置了ANDROID_COOKIE这个环境变量，从web 端F12拿的 Cookie

**Comment by neverno** [comment]
我也是这个错误，希望 @Chasing66 修复下！

**Comment by IanSmith123** [comment]
当前的 main 分支的代码需要的是通过安卓端抓取的 cookie。浏览器端抓 cookie 的代码在 old分支，不一定还能使用。

FYI: Android 抓包的这部分结果如下，你可以尝试把他追加到浏览器端抓的 cookie 里面，万一可以用呢（虽然我感觉希望不太大） :)
```
device_smzdm=android;device_smzdm_version=10.6.10;device_smzdm_version_code=930;
```

**Comment by Theoshen** [comment]
@IanSmith123 确实用不了
```
[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
2023-12-12 16:31:50.861 | INFO     | __main__:load_conf:25 - Get configration from env
Traceback (most recent call last):
  File "/ql/data/repo/Chasing66_smzdm_bot/app/main.py", line 81, in <module>
    main()
  File "/ql/data/repo/Chasing66_smzdm_bot/app/main.py", line 69, in main
    msg += tasks.checkin()
  File "/ql/data/repo/Chasing66_smzdm_bot/app/utils/smzdm_tasks.py", line 15, in checkin
    resp = self.bot.request("POST", url)
  File "/ql/data/repo/Chasing66_smzdm_bot/app/utils/smzdm_bot.py", line 92, in request
    data = self.data(extra_data)
  File "/ql/data/repo/Chasing66_smzdm_bot/app/utils/smzdm_bot.py", line 83, in data
    "token": self.cookies_dict["sess"],
KeyError: 'sess'

## 执行结束... 2023-12-12 16:31:57  耗时 8 秒　　
```

**Comment by enwaiax** [comment]
统一回复一下：暂时没时间修复，有空了会尽快修复

**Comment by enwaiax** [comment]
最新版本可以 work 了
